<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TelemetryApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.32.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.80.0" />
    <PackageReference Include="Grpc.Tools" Version="2.80.0" PrivateAssets="All" />

    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.13.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\telemetry-contracts\telemetry-contracts.csproj" />
  </ItemGroup>

  <!-- gRPC generated clients -->
  <ItemGroup>
    <Protobuf Include="Protos\telemetry.proto"
              GrpcServices="Client"
              Link="Protos\telemetry.proto" />

    <Protobuf Include="Protos\insights.proto"
              GrpcServices="Client"
              Link="Protos\insights.proto" />
  </ItemGroup>

</Project>
