// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: proto/insights.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightsRequest) Reset() {
	*x = InsightsRequest{}
	mi := &file_proto_insights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightsRequest) ProtoMessage() {}

func (x *InsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightsRequest.ProtoReflect.Descriptor instead.
func (*InsightsRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{0}
}

type DeviceInsight struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AvgSpeed       float64                `protobuf:"fixed64,2,opt,name=avg_speed,json=avgSpeed,proto3" json:"avg_speed,omitempty"`
	AvgTemperature float64                `protobuf:"fixed64,3,opt,name=avg_temperature,json=avgTemperature,proto3" json:"avg_temperature,omitempty"`
	AvgBattery     float64                `protobuf:"fixed64,4,opt,name=avg_battery,json=avgBattery,proto3" json:"avg_battery,omitempty"`
	TotalEvents    int32                  `protobuf:"varint,5,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceInsight) Reset() {
	*x = DeviceInsight{}
	mi := &file_proto_insights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInsight) ProtoMessage() {}

func (x *DeviceInsight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInsight.ProtoReflect.Descriptor instead.
func (*DeviceInsight) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInsight) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInsight) GetAvgSpeed() float64 {
	if x != nil {
		return x.AvgSpeed
	}
	return 0
}

func (x *DeviceInsight) GetAvgTemperature() float64 {
	if x != nil {
		return x.AvgTemperature
	}
	return 0
}

func (x *DeviceInsight) GetAvgBattery() float64 {
	if x != nil {
		return x.AvgBattery
	}
	return 0
}

func (x *DeviceInsight) GetTotalEvents() int32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type InsightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInsight       `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsightsResponse) Reset() {
	*x = InsightsResponse{}
	mi := &file_proto_insights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsightsResponse) ProtoMessage() {}

func (x *InsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsightsResponse.ProtoReflect.Descriptor instead.
func (*InsightsResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{2}
}

func (x *InsightsResponse) GetDevices() []*DeviceInsight {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_proto_insights_proto protoreflect.FileDescriptor

const file_proto_insights_proto_rawDesc = "" +
	"\n" +
	"\x14proto/insights.proto\x12\x12telemetry.insights\"\x11\n" +
	"\x0fInsightsRequest\"\xb6\x01\n" +
	"\rDeviceInsight\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tavg_speed\x18\x02 \x01(\x01R\bavgSpeed\x12'\n" +
	"\x0favg_temperature\x18\x03 \x01(\x01R\x0eavgTemperature\x12\x1f\n" +
	"\vavg_battery\x18\x04 \x01(\x01R\n" +
	"avgBattery\x12!\n" +
	"\ftotal_events\x18\x05 \x01(\x05R\vtotalEvents\"O\n" +
	"\x10InsightsResponse\x12;\n" +
	"\adevices\x18\x01 \x03(\v2!.telemetry.insights.DeviceInsightR\adevices2j\n" +
	"\x0eDeviceInsights\x12X\n" +
	"\vGetInsights\x12#.telemetry.insights.InsightsRequest\x1a$.telemetry.insights.InsightsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_insights_proto_rawDescOnce sync.Once
	file_proto_insights_proto_rawDescData []byte
)

func file_proto_insights_proto_rawDescGZIP() []byte {
	file_proto_insights_proto_rawDescOnce.Do(func() {
		file_proto_insights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_insights_proto_rawDesc), len(file_proto_insights_proto_rawDesc)))
	})
	return file_proto_insights_proto_rawDescData
}

var file_proto_insights_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_insights_proto_goTypes = []any{
	(*InsightsRequest)(nil),  // 0: telemetry.insights.InsightsRequest
	(*DeviceInsight)(nil),    // 1: telemetry.insights.DeviceInsight
	(*InsightsResponse)(nil), // 2: telemetry.insights.InsightsResponse
}
var file_proto_insights_proto_depIdxs = []int32{
	1, // 0: telemetry.insights.InsightsResponse.devices:type_name -> telemetry.insights.DeviceInsight
	0, // 1: telemetry.insights.DeviceInsights.GetInsights:input_type -> telemetry.insights.InsightsRequest
	2, // 2: telemetry.insights.DeviceInsights.GetInsights:output_type -> telemetry.insights.InsightsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_insights_proto_init() }
func file_proto_insights_proto_init() {
	if File_proto_insights_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_insights_proto_rawDesc), len(file_proto_insights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_insights_proto_goTypes,
		DependencyIndexes: file_proto_insights_proto_depIdxs,
		MessageInfos:      file_proto_insights_proto_msgTypes,
	}.Build()
	File_proto_insights_proto = out.File
	file_proto_insights_proto_goTypes = nil
	file_proto_insights_proto_depIdxs = nil
}
